### ISSUE TITLE
How is it possible to localize "Close", "Clear" & "Apply" buttons and input string from..to

### ISSUE THREAD

**Issue by maxfarseer** [n1k0/elm-daterange-picker#15]
Hello! Thank you for your package. I found some functions in config, which can help me to work on international version.
So, here we are:
- monthFormatter - months
- predefinedRanges - ranges
- weekdayFormatter - week days

What I miss:
- action buttons at the bottom
- text in input, for example: `from 2020-11-12 to 2020-11-21` and I need `DD/MM/YYYY - DD/MM/YYYY`

Any suggestions?

**Comment by maxfarseer** [comment]
https://github.com/allo-media/elm-daterange-picker/pull/16

**Comment by n1k0** [comment]
Fixed in #16 and released under a new package namespace here https://package.elm-lang.org/packages/n1k0/elm-daterange-picker/latest/
